### PR TITLE
reana: transformed into a full reana demo

### LINKED ISSUE #4: REANA configuration
Add fully working `reana.yaml` set up example.

### LINKED ISSUE #6: better workflow names
Rename workflow steps to have more meaningful step names:

- `step1data` -> `analyse_data`
- `step1mc` -> `analyse_mc`
- `step2` -> `make_plot`

as discussed briefly with @clelange. Any better naming suggestions?

### LINKED ISSUE #7: better docs
Expand physics information in the documentation.

### LINKED ISSUE #9: analysis: code/data/results reorganisation
Reogranise directory into code/data/results, simplify main README.rst, propagate local CWL/Yadage usage instructions to corresponding yaml files, amend inputs/workflow/outputs order in reana.yaml files, remove author emails, see https://github.com/reanahub/reana-demo-worldpopulation/pull/25 for example of things to do.

### PR DESCRIPTION
**Pull request by dprelipcean**
* Added serial and fixed cwl workflows (Closes #4)

* Improved docs from cod (Closes #7)

* Changed workflow names (Closes #6)

* Reorganized project structure (Closes #9)

Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
I see a trouble running example in REANA:

```
2019-09-13 15:15:28,442 | cwltool | MainThread | INFO | [workflow ] starting step analyse_data
2019-09-13 15:15:28,442 | cwltool | MainThread | INFO | [step analyse_data] start
2019-09-13 15:21:37,450 | cwltool | analyse_mc | INFO | [step analyse_mc] completed success
2019-09-13 15:23:02,300 | cwltool | analyse_data | INFO | [step analyse_data] completed success
2019-09-13 15:23:02,558 | cwltool | MainThread | INFO | [workflow ] starting step make_plot
2019-09-13 15:23:02,558 | cwltool | MainThread | INFO | [step make_plot] start
ERROR Exception on step 'make_plot'
2019-09-13 15:23:02,740 | cwltool | MainThread | ERROR | Exception on step 'make_plot'
ERROR [step make_plot] Cannot make job: workflow.json:1:1777: Expression evaluation error:
workflow.json:1:1777: Syntax error in parameter reference 'data.DoubleMuParked2012C_10000_Higgs.path': data is not defined. This could be due to using Javascript code without specifying InlineJavascriptRequirement.
2019-09-13 15:23:02,742 | cwltool | MainThread | ERROR | [step make_plot] Cannot make job: workflow.json:1:1777: Expression evaluation error:
workflow.json:1:1777: Syntax error in parameter reference 'data.DoubleMuParked2012C_10000_Higgs.path': data is not defined. This could be due to using Javascript code without specifying InlineJavascriptRequirement.
```

I also see in the logs:

```
WORKFLOW ENGINE LOGS
ERROR Exception on step 'make_plot'
ERROR [step make_plot] Cannot make job: workflow.json:1:1777: Expression evaluation error:
workflow.json:1:1777: Syntax error in parameter reference 'data.DoubleMuParked2012C_10000_Higgs.path': data is not defined. This could be due to using Javasc>
WARNING Final process status is permanentFail
{'mass4l_combine_userlvl3.pdf': None}
```

A wrong specs for the file?

```console
$ git grep DoubleMuParked2012C_10000_Higgs.path
workflow/make_plot.cwl:45:      cp $(data.DoubleMuParked2012C_10000_Higgs.path) ../../../../results
```

**Comment by dprelipcean** [comment]
Amended the changes.

Note: To run it locally (outside reana), one would have to change the workflow files as follow:
1) Remove the `cms` environemnt entrypoint, i.e. remove the lines:
```console
      source /opt/cms/cmsset_default.sh
      scramv1 project CMSSW CMSSW_5_3_32
      cd CMSSW_5_3_32/src
      eval `scramv1 runtime -sh`
```
2) Adjust the project structure, as two directory levels are missing, i.e. change:
`cp -r ../../../../code/HiggsExample20112012 .` to `cp -r ../../code/HiggsExample20112012 .`

**Comment by dprelipcean** [comment]
Not sure if something changed, but I get a connection error with `kubernetes`.

I am using exactly the same code that used to work, and looking at the `job-controller` logs I get:
```console
2019-09-16 16:19:01,979 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854e6f0d68>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/batch/v1/jobs?watch=True
2019-09-16 16:19:01,979 | urllib3.connectionpool | kubernetes_job_monitor | WARNING | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854e6f0d68>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/batch/v1/jobs?watch=True
2019-09-16 16:19:01,988 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854e6f0b38>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/batch/v1/jobs?watch=True
2019-09-16 16:19:01,988 | urllib3.connectionpool | kubernetes_job_monitor | WARNING | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854e6f0b38>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/batch/v1/jobs?watch=True
2019-09-16 16:19:01,991 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854e6f0ba8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/batch/v1/jobs?watch=True
2019-09-16 16:19:01,991 | urllib3.connectionpool | kubernetes_job_monitor | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854e6f0ba8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /apis/batch/v1/jobs?watch=True
2019-09-16 16:19:02,003 | root | kubernetes_job_monitor | ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f854e6f9c50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/reana_job_controller/job_monitor.py", line 63, in watch_jobs
    current_k8s_batchv1_api_client.list_job_for_all_namespaces
  File "/usr/local/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 132, in stream
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/batch_v1_api.py", line 526, in list_job_for_all_namespaces
    (data) = self.list_job_for_all_namespaces_with_http_info(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/batch_v1_api.py", line 623, in list_job_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 355, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.96.0.1', port=443): Max retries exceeded with url: /apis/batch/v1/jobs?watch=True (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854e6f9c50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by tiborsimko** [comment]
Status:

- the serial debugging workflow works fine on moderate 4 core 8 GB laptop;
- the parallel CWL workflow kills the minikube.

I'll rename the debugging yaml file and merge.

**Pull request merged**
